Resource overview section added [WIP]
simpleanalytics/marketing-site pull request #3
Opened 2023-06-01 01:37 UTC by Atiksh04

I've added changes for the resource overview section with the following sub-sections:
- Alternatives
- Comparisons
- Analytics Review
- Analytics Pricing
Have added subpages to these sections as per the requirement.

2023-06-01 14:29 UTC, adriaanvanrossum requested changes
It looks already excellent, I just have a few nitpick things. Some code is double (and I know, I did have that as well), but if we work with the two of us in the same code base, it's nicer to not have (too much) duplicate logic. Using prettier will fix some code styling "issues" as well, so we have a solution for that as well.

Don't forget to create a PR for Strapi to add the hard-coded article types.

2023-06-01 14:29 UTC, adriaanvanrossum commented on pages/resources/alternatives/index.vue
> +const getFlagUrl = (locale) => {
We could move this function to `utils/miscellaneous.js`, after that, you can use it anywhere without importing. I already have it copied, but 3 times is a bit too much.

2023-06-01 14:29 UTC, adriaanvanrossum commented on pages/resources/analytics-pricing/index.vue
> +const getFlagUrl = (locale) => {
Same, use `utils/miscellaneous.js`

2023-06-01 14:29 UTC, adriaanvanrossum commented on pages/resources/analytics-review/index.vue
> +const getFlagUrl = (locale) => {
Same, use `utils/miscellaneous.js`

2023-06-07 21:20 UTC, Atiksh04 commented on pages/resources/alternatives/index.vue
> +const getFlagUrl = (locale) => {
I have updated this, please have a look

2023-06-07 21:20 UTC, Atiksh04 commented on pages/resources/analytics-pricing/[slug].vue
> +<Article
I have updated this, please have a look

2023-06-07 21:20 UTC, Atiksh04 commented on pages/resources/analytics-pricing/index.vue
> +const getFlagUrl = (locale) => {
Updated this, please have a look

2023-06-07 21:20 UTC, Atiksh04 commented on pages/resources/analytics-review/index.vue
> +const getFlagUrl = (locale) => {
This is also updated

2023-06-08 10:25 UTC, Atiksh04 commented on pages/resources/alternatives/index.vue
> +const getFlagUrl = (locale) => {
have resolved this

2023-06-08 13:01 UTC, merged