Utm Builder pages changes
simpleanalytics/marketing-site pull request #5
Opened 2023-06-24 22:47 UTC by Atiksh04

I have made changes to the UTM Builder overview section and created separate builder pages for:

- TikTok
- Google Spreadsheet
- Facebook
- Twitter
- Google
- Spreadsheet

Each independent page container's "intro_text" has already been translated, and the content shown after the generator form is fetched from Strapi CMS.

In Strapi, I have added the articleType as "utm-builder". To fetch content for the builder pages, the slug value should match the following:

- utm-builder-twitter
- utm-builder-tiktok
- utm-builder-google-spreadsheet
- utm-builder-google
- utm-builder-facebook
- utm-builder-spreadsheet

The slug that we add on Strapi(while creating an article) should match these slug values because we use them as parameters while fetching content from the CMS. Since there is only a static list of UTM Builder types, using hardcoded values like these will ensure that there is only one article on Strapi for each utm-builder page. 
I have also shared these slug values with Iron.

2023-06-26 13:57 UTC, adriaanvanrossum requested changes
Good job! Thanks a lot. Added a few comments on specific lines.

One design thing: add more line spacing here:

<kbd><img width="1440" alt="Screenshot" src="https://github.com/simpleanalytics/marketing-site/assets/1079135/4d9b6826-afd5-4989-ab92-8f3c84a81749"></kbd>

Usually `leading-loose` is fine.

2023-06-26 13:57 UTC, adriaanvanrossum commented on components/Article.vue
> +if(!props.hideSeoMeta){
Did you install prettier? This would have been fixed by prettier itself. Just install it in some way and make it "format on save".

2023-06-27 04:53 UTC, Atiksh04 commented on components/Article.vue
> +          <NuxtLink class="button" :to="localePath({ name: getTypeFromArticleName() === 'glossary' ? 'glossary' : getTypeFromArticleName() === 'resources' ? 'resources' : 'utm-builder' })"
please check have updated this

2023-06-27 04:53 UTC, Atiksh04 commented on components/Article.vue
> +if(!props.hideSeoMeta){
I have updated the editor settings now, so this issue should not happen again

2023-06-27 04:53 UTC, Atiksh04 commented on components/logos/SpreadSheet.vue
> +      style="opacity: 0.999"
have updated this

2023-06-27 04:53 UTC, Atiksh04 commented on pages/resources/alternatives/index.vue
> +console.log('--articles---', articles)
:-)

2023-06-27 13:09 UTC, adriaanvanrossum requested changes
Only a few leading issues

2023-06-28 08:52 UTC, Atiksh04 commented on pages/utm-builder/index.vue
> +      <h1 class="text-4xl font-medium sm:text-5xl md:text-6xl">
have updated this

2023-06-28 08:52 UTC, Atiksh04 commented on pages/utm-builder/index.vue
> +      <p class="mt-8 text-lg">
have updated this

2023-06-28 08:52 UTC, Atiksh04 commented on pages/utm-builder/[slug].vue
> +        class="mt-8 text-md"
have updated this

2023-06-28 10:01 UTC, adriaanvanrossum commented
Sorry, one more thing. This footer link does not translate:

<img width="998" alt="image" src="https://github.com/simpleanalytics/marketing-site/assets/1079135/2da67ad0-3c86-4d18-b430-769a3bff8f0a">

```
[intlify] Not found 'home.footer.resources' key in 'de' locale messages.                                                                                                                                                                                                                                      11:58:30
[intlify] Fall back to translate 'home.footer.resources' key with 'en' locale.
```

For all non EN language

2023-06-28 11:13 UTC, Atiksh04 commented
> Sorry, one more thing. This footer link does not translate:
> 
> <img alt="image" width="998" src="https://user-images.githubusercontent.com/1079135/249428088-2da67ad0-3c86-4d18-b430-769a3bff8f0a.png">
> ```
> [intlify] Not found 'home.footer.resources' key in 'de' locale messages.                                                                                                                                                                                                                                      11:58:30
> [intlify] Fall back to translate 'home.footer.resources' key with 'en' locale.
> ```
> 
> For all non EN language

have added these translations, please have a look

2023-06-28 12:08 UTC, merged